ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'TELEGRAM';
ALTER TABLE "Conversation" ADD COLUMN "telegramConnectionId" VARCHAR(180),
  ADD COLUMN "telegramChatId" VARCHAR(32),
  ADD COLUMN "telegramLastInboundAt" TIMESTAMP(3),
  ADD COLUMN "telegramRevision" INTEGER NOT NULL DEFAULT 0;
CREATE TABLE "TelegramInboxEvent" (
  "id" VARCHAR(120) NOT NULL PRIMARY KEY,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
